services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: /etc/envs/property-scraper.env
    ports:
      - "10000:10000"
    restart: unless-stopped
    profiles: [prod]

  app-local:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PROPERTY_API_DB_HOST: db-local
      PROPERTY_API_DB_PORT: 3306
      PROPERTY_API_DB_PASSWORD: password
      PROPERTY_API_APIKEY: abc123
    ports:
      - "127.0.0.1:10000:10000"
    profiles: [local]

  db-local:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: property_api
      MYSQL_USER: property-api
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    profiles: [local]

volumes:
  data:
